<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Commerce Site</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Welcome to My E-Commerce Site!</h1>
    <p>This is the beginning of our project with PHP!</p>

    <?php
        echo "<p>This is a message generated by PHP.</p>";
    ?>

    <button onclick="showMessage()">Click me!</button>

    <script src="script.js"></script>
    <?php
    // PostgreSQL veritabanına bağlanmak için
    $host = 'localhost';
    $db = 'your_database_name';
    $user = 'your_username';
    $password = 'your_password';

    $dsn = "pgsql:host=$host;port=5432;dbname=$db;user=$user;password=$password";

    try {
        // Veritabanı bağlantısını oluştur
        $pdo = new PDO($dsn);

        if($pdo) {
            echo "<p>Connected to the database successfully!</p>";
        }
    } catch (PDOException $e) {
        echo $e->getMessage();
    }
?>

</body>
</html>
